/* UNIVERSATLAS · dicionário INGLÊS (r232).
   Regras da casa: sem emoji, sem travessão. O português do index.html é a
   chave; o que não estiver aqui aparece em português (nunca quebra).
   ui: textos da interface (chave = texto exato em PT-BR, ou o innerHTML de um
       parágrafo inteiro do manual). nomes: nome de cada corpo por id.
   sis/gal/ceu: sistemas, galáxias e constelações por id. palavras: troca de
   palavra em designações compostas (SOL-3 · PLANETA vira SUN-3 · PLANET). */
window.I18N_EN = {
ui: {
  /* topo, status, escala */
  'EM ÓRBITA':'IN ORBIT', 'ESCALA ·':'SCALE ·', 'SISTEMA':'SYSTEM', 'CORPO':'BODY', 'GALÁXIA':'GALAXY', 'UNIVERSO':'UNIVERSE',
  'ESCALA MÁXIMA':'MAXIMUM SCALE', 'NAVEGANDO':'NAVIGATING', 'LINK TRAVADO':'LINK LOCKED', 'ALVO CATALOGADO':'TARGET CATALOGED',
  'VIA LÁCTEA':'MILKY WAY', 'SISTEMA SOLAR':'SOLAR SYSTEM', 'RETORNANDO À VISÃO DO SISTEMA':'RETURNING TO SYSTEM VIEW',
  'MAPA CÊNICO':'SCENIC MAP', 'ESCALA 1:1':'1:1 SCALE',
  'Alterna entre o mapa cênico e a escala 1:1 do sistema solar':'Switches between the scenic map and the 1:1 scale of the solar system',
  'Buscar':'Search', 'Registro de bordo':'Logbook', 'Mais opções':'More options', 'Objeto anterior':'Previous object', 'Objeto seguinte':'Next object',
  'Ver o sistema em outra data':'See the system on another date', 'Trilha sonora':'Soundtrack', 'Modo foto':'Photo mode', 'Tela cheia':'Full screen',
  'Linhas do mapa':'Map lines', 'Ajuda':'Help', 'Configurações':'Settings',
  'SAT LINK 08 · DESTINO':'SAT LINK 08 · TARGET', 'CAMPO DE VISÃO':'FIELD OF VIEW',
  'Pausar ou continuar o tempo':'Pause or resume time', 'Ir para uma data':'Go to a date',
  'Relógio travado no AGORA: clique para voltar ao vivo':'Clock locked to NOW: click to go back live', '● AO VIVO':'● LIVE', 'Velocidade do tempo':'Time speed',
  'Anterior':'Previous', 'Próximo':'Next', 'Próxima':'Next', 'Aproximar':'Zoom in', 'Afastar':'Zoom out', 'Toque para ocultar':'Tap to hide',
  'Sair do modo foto':'Exit photo mode', 'SAIR DO MODO FOTO':'EXIT PHOTO MODE',
  'TOQUE EM UM PLANETA PARA TRAVAR O LINK':'TAP A PLANET TO LOCK THE LINK', 'ESTABELECENDO LINK':'ESTABLISHING LINK',
  /* tour */
  'Escolher rota':'Choose a route', 'ROTA COMPLETA':'FULL ROUTE', 'MUNDOS DE ÁGUA':'WATER WORLDS', 'AS VIAJANTES':'THE VOYAGERS',
  'AS MORADAS DA VIDA':'THE HOMES OF LIFE', 'NEBULOSAS':'NEBULAE', 'GALÁXIAS':'GALAXIES', 'A CORRIDA DA LUA':'THE MOON RACE', 'AS FIGURAS DO CÉU':'THE FIGURES OF THE SKY',
  'Parada anterior':'Previous stop', 'Pausar e continuar':'Pause and resume', 'Próxima parada':'Next stop', 'Encerrar e voltar':'End and go back',
  '▸ ROTAS DO TOUR':'▸ TOUR ROUTES',
  'Sente e assista: a nave navega sozinha, sem cortes. Qualquer toque na cena devolve o controle. Rota concluída rende a conquista EXP-01.':'Sit back and watch: the ship navigates on its own, with no cuts. Any touch on the scene gives control back. A completed route earns the EXP-01 achievement.',
  'TOUR INICIADO · TOQUE NA CENA PARA ASSUMIR O CONTROLE':'TOUR STARTED · TAP THE SCENE TO TAKE CONTROL', 'TOUR ENCERRADO':'TOUR ENDED',
  'ROTA CONCLUÍDA · DE VOLTA AO SEU POSTO':'ROUTE COMPLETED · BACK TO YOUR POST', 'O mapa se guia sozinho':'The map guides itself', '▶ TOUR':'▶ TOUR',
  /* player */
  '♪ TRANSMISSÃO DE BORDO':'♪ ONBOARD TRANSMISSION', 'Tocar/Pausar':'Play/Pause', 'SOM: LIGADO':'SOUND: ON', 'SOM: DESLIGADO':'SOUND: OFF', 'Volume':'Volume',
  /* tutorial */
  '▸ TUTORIAL DE BORDO':'▸ ONBOARD TUTORIAL', 'PULAR':'SKIP', '◂ VOLTAR':'◂ BACK', 'PRÓXIMO ▸':'NEXT ▸', 'COMEÇAR ▸':'START ▸', 'CONCLUIR':'FINISH', 'ENTENDI':'GOT IT',
  'INICIAR A VIAGEM ▸':'START THE TRIP ▸',
  '<b>BEM-VINDO A BORDO, NAVEGADOR.</b><br>Um mapa vivo do nosso pedaço de universo, com dados reais e navegação livre. Quer um giro rápido pelos controles?':'<b>WELCOME ABOARD, NAVIGATOR.</b><br>A living map of our corner of the universe, with real data and free navigation. Want a quick spin through the controls?',
  'Arraste com um dedo para orbitar. Pince para aproximar.':'Drag with one finger to orbit. Pinch to zoom.',
  'Arraste para orbitar. Role para aproximar.':'Drag to orbit. Scroll to zoom.',
  'Arraste e gire o mapa':'Drag and spin the map', 'Aproxime ou afaste o zoom':'Zoom in or out',
  'As distâncias e os tamanhos são <b>cênicos</b>, desenhados para navegação. Os dados das fichas são reais.':'Distances and sizes are <b>scenic</b>, drawn for navigation. The data on the cards is real.',
  'Toque na <b>TERRA</b>, ou em qualquer planeta. O primeiro toque abre a ficha e trava a câmera nele.':'Tap <b>EARTH</b>, or any planet. The first tap opens its card and locks the camera on it.',
  'Clique na <b>TERRA</b>, ou em qualquer planeta. O primeiro clique abre a ficha e trava a câmera nele.':'Click <b>EARTH</b>, or any planet. The first click opens its card and locks the camera on it.',
  'Abra a ficha de um planeta':'Open a planet card', 'TERRA':'EARTH',
  'Agora toque em <b>ENTRAR</b> no topo da ficha, ou de novo no corpo.':'Now tap <b>ENTER</b> at the top of the card, or tap the body again.',
  'Entre no corpo':'Enter the body',
  'Para voltar, junte os dedos até a cena abrir, ou use o ESC.':'To go back, pinch in until the scene opens up, or press ESC.',
  'Para voltar, afaste o zoom até a cena abrir, ou use o ESC.':'To go back, zoom out until the scene opens up, or press ESC.',
  'Volte para a cena do sistema':'Return to the system scene',
  'Também dá para navegar pelo <b>rastro</b> aqui de cima: clique em <b>VIA LÁCTEA</b> para subir até a galáxia.':'You can also navigate through the <b>breadcrumb</b> up here: click <b>MILKY WAY</b> to go up to the galaxy.',
  'Suba para a galáxia':'Go up to the galaxy',
  'No celular, os botões extras moram no <b>⋯</b> aqui de cima. Toque nele para abrir o menu.':'On the phone, the extra buttons live in the <b>⋯</b> up here. Tap it to open the menu.',
  'Abra o menu ⋯':'Open the ⋯ menu',
  'O mapa da galáxia. Volte para casa pelo botão <b>« voltar</b> do menu, ou toque no <b>SISTEMA SOLAR</b> piscando no mapa e depois em ENTRAR.':'The galaxy map. Head home with the <b>« back</b> button in the menu, or tap the blinking <b>SOLAR SYSTEM</b> on the map and then ENTER.',
  'O mapa da galáxia. Agora volte para casa: clique no <b>SISTEMA SOLAR</b> (piscando) e depois em ENTRAR, ou use o botão « voltar.':'The galaxy map. Now head home: click the blinking <b>SOLAR SYSTEM</b> and then ENTER, or use the « back button.',
  'Volte ao Sistema Solar':'Return to the Solar System',
  'De novo o <b>⋯</b>: abra o menu para acharmos o filtro de camadas.':'The <b>⋯</b> again: open the menu so we can find the layers filter.',
  'Toque no <b>≋</b> do menu e LIGUE a linha das <b>SONDAS</b>. As rotas surgem no mapa.':'Tap <b>≋</b> in the menu and turn ON the <b>PROBES</b> line. Their routes appear on the map.',
  'Filtros: abra o <b>≋</b> e LIGUE a linha das <b>SONDAS</b>. As rotas surgem no mapa. Cada filtro liga ou desliga uma camada.':'Filters: open <b>≋</b> and turn ON the <b>PROBES</b> line. Their routes appear on the map. Each filter turns a layer on or off.',
  'Ligue a linha das SONDAS':'Turn on the PROBES line',
  'Seu painel de bordo: <b>CAMPO DE VISÃO</b> é a largura real da tela; abaixo, o endereço no espaço (cênico, ou RA/DEC, altere nas configurações); <b>T+</b> é o tempo da sua sessão; e abaixo a <b>data real do sistema solar</b>, com opção de pausar ou viajar pelo tempo.':'Your dashboard: <b>FIELD OF VIEW</b> is the real width of the screen; below it, your address in space (scenic, or RA/DEC, change it in the settings); <b>T+</b> is your session time; and below, the <b>real date of the solar system</b>, with the option to pause or travel through time.',
  'Aqui temos o menu: navegação, música e sons, modo foto, filtros, diário de bordo, pesquisa e ajuda. O <b>?</b> guarda o manual.':'Here is the menu: navigation, music and sounds, photo mode, filters, logbook, search and help. The <b>?</b> holds the manual.',
  'Uma última coisa, e talvez a melhor. O que você está vendo é o <b>MAPA CÊNICO</b>: as distâncias e os tamanhos foram desenhados para caber na tela e os planetas ficarem grandes o bastante para admirar. Bonito, mas não é o tamanho de verdade.<br><br>Existe a <b>ESCALA 1:1</b>, onde tudo está na medida real: os planetas viram grãos de poeira, as distâncias são honestas, o céu ganha as estrelas nas posições verdadeiras e dá para afastar até ver a Via Láctea inteira. É outro mundo.<br><br>Troque quando quiser neste botão aqui em cima.':'One last thing, and maybe the best. What you are seeing is the <b>SCENIC MAP</b>: distances and sizes were drawn to fit the screen and to keep the planets big enough to admire. Beautiful, but not the true size.<br><br>There is the <b>1:1 SCALE</b>, where everything is at real measure: planets become grains of dust, distances are honest, the sky gets the stars in their true positions, and you can zoom out until you see the whole Milky Way. It is another world.<br><br>Switch whenever you like with this button up here.',
  '<b>COMPARAR:</b> o primeiro corpo ficou marcado. Agora abra qualquer outro, pela busca, pelo mapa ou pelo registro, e toque em <b>◫ COMPARAR</b> de novo: a análise sai em escala real.':'<b>COMPARE:</b> the first body is marked. Now open any other one, through search, the map or the logbook, and tap <b>◫ COMPARE</b> again: the analysis comes out at real scale.',
  'Experimente: busque <b>MARTE</b> e compare. Quando a diferença é grande, o menor aparece DENTRO do maior.':'Try it: search <b>MARS</b> and compare. When the difference is large, the smaller one appears INSIDE the larger one.',
  'TUTORIAIS RESETADOS':'TUTORIALS RESET', 'CONQUISTAS RESETADAS':'ACHIEVEMENTS RESET',
  /* bancada */
  '◉ A BANCADA · MUNDOS LADO A LADO':'◉ THE BENCH · WORLDS SIDE BY SIDE', 'Copiar o link desta bancada':'Copy the link to this bench',
  'ADICIONAR UM CORPO À BANCADA...':'ADD A BODY TO THE BENCH...',
  'Os globos giram com o motor de verdade do mapa, na inclinação real de cada eixo. Toque num nome para pô-lo ou tirá-lo da bancada (até doze; a fileira rola de lado).':'The globes spin with the real engine of the map, at the true tilt of each axis. Tap a name to add it to or remove it from the bench (up to twelve; the row scrolls sideways).',
  'HABITÁVEIS':'HABITABLE', 'ROCHOSOS':'ROCKY', 'GIGANTES':'GIANTS', 'LUAS GRANDES':'LARGE MOONS', 'AS ESTRELAS':'THE STARS', 'LUAS DE JÚPITER':'MOONS OF JUPITER', 'PERSONALIZADO':'CUSTOM',
  'TAMANHO EM ESCALA':'SIZE TO SCALE', 'FORA DE ESCALA':'NOT TO SCALE', 'LINK DA BANCADA COPIADO · cole e envie':'BENCH LINK COPIED · paste and send',
  /* eventos */
  '◈ EVENTOS DO CÉU':'◈ SKY EVENTS', 'BUSCAR EVENTO...':'SEARCH EVENTS...',
  'Escolher um evento leva o relógio do sistema para o instante dele. Datas com ·aprox são aproximadas.':'Choosing an event takes the system clock to its exact moment. Dates marked ·aprox are approximate.',
  'TODOS':'ALL', 'ECLIPSES':'ECLIPSES', 'TRÂNSITOS':'TRANSITS', 'ESTAÇÕES':'SEASONS', 'PLANETAS':'PLANETS', 'COMETAS':'COMETS', 'MARCOS':'MILESTONES',
  'DAQUI PARA A FRENTE':'FROM NOW ON', 'JÁ ACONTECERAM':'ALREADY HAPPENED', 'SAIU DO TEMPO REAL':'LEFT REAL TIME', 'AO VIVO · O RELÓGIO CORRE NO AGORA':'LIVE · THE CLOCK RUNS ON NOW',
  /* data */
  'VER O SISTEMA EM OUTRA DATA':'SEE THE SYSTEM ON ANOTHER DATE', 'DIA':'DAY', 'MÊS':'MONTH', 'ANO':'YEAR', 'HORA':'HOUR', 'MIN':'MIN',
  'VER NESSA DATA':'GO TO THIS DATE', 'HOJE':'TODAY', '◈ ESCOLHER UM EVENTO DO CÉU':'◈ PICK A SKY EVENT',
  /* configurações */
  '⚙︎ CONFIGURAÇÕES':'⚙︎ SETTINGS', 'VELOCIDADE DO TEMPO':'TIME SPEED', 'TEMPO REAL · TRAVADO NO AGORA':'REAL TIME · LOCKED TO NOW',
  '1 SEGUNDO = 1 SEGUNDO':'1 SECOND = 1 SECOND', '1 SEGUNDO = 1 HORA':'1 SECOND = 1 HOUR', '1 SEGUNDO = 1 DIA':'1 SECOND = 1 DAY',
  '1 SEGUNDO = 1 SEMANA':'1 SECOND = 1 WEEK', '1 SEGUNDO = 1 MÊS':'1 SECOND = 1 MONTH', 'AO VIVO · 1 SEGUNDO = 1 SEGUNDO':'LIVE · 1 SECOND = 1 SECOND',
  '1 SEM':'1 WK', '1 MÊS':'1 MO', 'EXTRAS':'EXTRAS', 'IDIOMA · LANGUAGE':'LANGUAGE · IDIOMA',
  'VIAGEM INTERPLANETAR NO TOUR (EXPERIMENTAL)':'INTERPLANETARY TRAVEL IN THE TOUR (EXPERIMENTAL)',
  'SISTEMA SOLAR EM ESCALA 1:1 (EXPERIMENTAL)':'SOLAR SYSTEM AT 1:1 SCALE (EXPERIMENTAL)', 'COORDENADAS REAIS (RA/DEC)':'REAL COORDINATES (RA/DEC)',
  'EFEITO LIGHTSPEED NAS VIAGENS 1:1 (EXPERIMENTAL)':'LIGHTSPEED EFFECT ON 1:1 TRAVEL (EXPERIMENTAL)',
  'DESLIGADO':'OFF', 'LIGADO':'ON', 'DESLIGADA':'OFF', 'LIGADA':'ON', 'DESLIGADOS':'OFF', 'LIGADOS':'ON', 'ATIVA':'ACTIVE', 'VISÍVEL':'VISIBLE', 'OCULTO':'HIDDEN',
  'SOM':'SOUND', 'MÚSICA':'MUSIC', 'EFEITOS SONOROS':'SOUND EFFECTS',
  'O relógio no canto inferior esquerdo mostra a data do sistema. Pausar e viajar no tempo ficam lá.':'The clock in the bottom left corner shows the system date. Pausing and time travel live there.',
  'LIGHTSPEED LIGADO: ACELERE FUNDO NO 1:1 PARA VER':'LIGHTSPEED ON: ZOOM HARD IN 1:1 TO SEE IT', 'LIGHTSPEED DESLIGADO':'LIGHTSPEED OFF',
  'ESCALA 1:1: distâncias, tamanhos e órbitas verdadeiros. Procure os planetas pelos RÓTULOS e acelere o RELÓGIO para ver Mercúrio correr.':'1:1 SCALE: true distances, sizes and orbits. Find the planets by their LABELS and speed up the CLOCK to watch Mercury run.',
  'ESCALA CÊNICA RESTAURADA':'SCENIC SCALE RESTORED',
  /* filtro */
  '≋ LINHAS DO MAPA':'≋ MAP LINES', 'PLANETAS ANÕES':'DWARF PLANETS', 'ASTEROIDES':'ASTEROIDS', 'ESTRELAS COMPANHEIRAS':'COMPANION STARS', 'LUAS':'MOONS',
  'COMETAS E VISITANTES':'COMETS AND VISITORS', 'SONDAS':'PROBES', 'SATÉLITES':'SATELLITES', 'MISSÕES TRIPULADAS':'CREWED MISSIONS', 'CINTURÕES':'BELTS',
  'Esconde só a linha. O corpo selecionado sempre mostra a própria rota.':'Hides only the line. The selected body always shows its own route.',
  '◌ OBJETOS NO MAPA':'◌ OBJECTS ON THE MAP',
  'Some com o objeto inteiro: corpo, rótulo e rota. Planetas e luas ficam sempre.':'Hides the whole object: body, label and route. Planets and moons always stay.',
  '✦ CAMADAS DO MAPA':'✦ MAP LAYERS', 'CONSTELAÇÕES NO CÉU REAL':'CONSTELLATIONS IN THE REAL SKY', 'NOMES DAS ESTRELAS NO CÉU':'STAR NAMES IN THE SKY',
  'ZONA HABITÁVEL DA ESTRELA':"THE STAR'S HABITABLE ZONE", 'RÉGUA DE DISTÂNCIAS (ESCALA 1:1)':'DISTANCE RULER (1:1 SCALE)', 'ECLÍPTICA E ZODÍACO':'ECLIPTIC AND ZODIAC',
  'DISCO DA RÉGUA':'RULER DISC', 'COR DA RÉGUA':'RULER COLOR', 'Azul-água':'Aqua', 'Azul da casa':'House blue', 'Verde-água':'Teal', 'Lilás':'Lilac', 'Âmbar':'Amber',
  'Escolher qualquer cor':'Pick any color', 'RASTRO DE 30 DIAS':'30-DAY TRAIL',
  /* linha do tempo */
  'Velocidade':'Speed', 'Terra girando ou parada durante a missão':'Earth spinning or still during the mission', 'Encerrar':'End',
  'TERRA GIRANDO: 1 volta por dia de missão':'EARTH SPINNING: 1 turn per mission day', 'TERRA PARADA: só a rota se move':'EARTH STILL: only the route moves',
  'LINHA DO TEMPO · A CENA CONTINUA LIVRE: ARRASTE E DÊ ZOOM À VONTADE':'TIMELINE · THE SCENE STAYS FREE: DRAG AND ZOOM AT WILL',
  /* card */
  '⬢ LINK TRAVADO':'⬢ LINK LOCKED', 'MODO MAPA':'MAP MODE', 'Fechar esta ficha':'Close this card', 'Fechar o Sistema Solar e olhar a galáxia':'Close the Solar System and look at the galaxy',
  'FOTO':'PHOTO', 'DESENHO':'DRAWING', 'Alternar entre a foto de verdade e o mapa desenhado':'Switch between the real photo and the drawn map',
  'LINHA DO TEMPO':'TIMELINE', 'Percorrer a rota no tempo':'Travel the route through time',
  '▶ ENTRAR · TRAVAR LINK':'▶ ENTER · LOCK LINK', '▶ ENTRAR · TRAVAR ROTA':'▶ ENTER · LOCK ROUTE',
  '◉ MUNDOS HABITÁVEIS LADO A LADO':'◉ HABITABLE WORLDS SIDE BY SIDE', '◉ PÔR NA BANCADA':'◉ PUT ON THE BENCH', '◎ VER A GALÁXIA DE CIMA':'◎ SEE THE GALAXY FROM ABOVE',
  'IR PARA':'GO TO', '≋ VER A LINHA DO TEMPO':'≋ SEE THE TIMELINE', '◈ FECHAR O SISTEMA PLANETÁRIO':'◈ CLOSE THE PLANETARY SYSTEM', '◈ VER O SISTEMA PLANETÁRIO':'◈ SEE THE PLANETARY SYSTEM',
  '← VOLTAR A ':'← BACK TO ', 'LUAS DE ':'MOONS OF ', 'LUAS · ':'MOONS · ', ' CONFIRMADAS':' CONFIRMED', ' CONFIRMADA':' CONFIRMED', ' VISITADOS':' VISITED', 'TOQUE P/ VISITAR':'TAP TO VISIT',
  'LUAS DO PASSADO · ':'MOONS OF THE PAST · ', 'DESATIVADO · SÓ REGISTRO':'DECOMMISSIONED · RECORD ONLY', 'Ver a linha do tempo':'See the timeline',
  ' ATIVOS · ':' ACTIVE · ', ' NO REGISTRO':' ON RECORD', 'PROGRAMA LUNA · URSS':'LUNA PROGRAM · USSR', 'ERA APOLLO · EUA':'APOLLO ERA · USA',
  'A NOVA CORRIDA · CHINA, JAPÃO E ARTEMIS':'THE NEW RACE · CHINA, JAPAN AND ARTEMIS', 'MISSÕES LUNARES':'LUNAR MISSIONS', ' · ≋ VÊ A VIAGEM':' · ≋ SEE THE TRIP',
  'SONDAS LANÇADAS DAQUI':'PROBES LAUNCHED FROM HERE', ' · ≋ VÊ A ROTA':' · ≋ SEE THE ROUTE', 'AS VISITAS · 1966 A HOJE':'THE VISITS · 1966 TO TODAY', ' · ≋ CADA VIAGEM':' · ≋ EACH TRIP',
  'ÍNDICE DE HABITABILIDADE':'HABITABILITY INDEX', 'GRAVIDADE (REF. TERRA)':'GRAVITY (EARTH = 1)', 'RECOLHER DADOS ▴':'COLLAPSE DATA ▴', 'EXPANDIR DADOS ▾':'EXPAND DATA ▾',
  'CURIOSIDADES':'FUN FACTS', 'NA FICÇÃO':'IN FICTION',
  'ROTA INDISPONÍVEL: dados de navegação insuficientes. Sonda em trânsito.':'ROUTE UNAVAILABLE: insufficient navigation data. Probe in transit.',
  '← VOLTAR AO PANORAMA':'← BACK TO OVERVIEW', '. Afaste o zoom para subir de escala.':'. Zoom out to go up a scale.', 'AGORA · ':'NOW · ', ' ILUMINADA':' ILLUMINATED',
  '◫ COMPARAR ESTE CORPO':'◫ COMPARE THIS BODY', '◫ COMPARAR COM ':'◫ COMPARE WITH ', '◫ CANCELAR COMPARAÇÃO':'◫ CANCEL COMPARISON',
  'COMPARAÇÃO CANCELADA':'COMPARISON CANCELED', 'AGORA ABRA OUTRO CORPO E TOQUE EM ◫':'NOW OPEN ANOTHER BODY AND TAP ◫', 'COMPARAR: ESCOLHA O SEGUNDO CORPO':'COMPARE: PICK THE SECOND BODY',
  'MAPA FOTOGRAFADO (NASA)':'PHOTOGRAPHED MAP (NASA)', 'MAPA DESENHADO À MÃO':'HAND-DRAWN MAP',
  'TOQUE DE NOVO PARA ENTRAR · OU USE O BOTÃO DO CARD':'TAP AGAIN TO ENTER · OR USE THE CARD BUTTON', 'TOQUE EM UMA GALÁXIA':'TAP A GALAXY',
  'DE VOLTA PARA CASA':'BACK HOME', 'ESCALA 1:1 · O MESMO LUGAR, AGORA NUM MAPA SÓ':'1:1 SCALE · THE SAME PLACE, NOW ON A SINGLE MAP',
  'A VIA LÁCTEA VISTA DE CIMA · O SISTEMA SOLAR FICA NUM BRAÇO':'THE MILKY WAY FROM ABOVE · THE SOLAR SYSTEM SITS IN AN ARM',
  'SISTEMA PLANETÁRIO: o corpo vira o centro e as luas orbitam no período real':'PLANETARY SYSTEM: the body becomes the center and the moons orbit in their real period',
  'ESCALA 1:1 · OS CORPOS VIRAM POEIRA':'1:1 SCALE · BODIES BECOME DUST', 'ESCALA CÊNICA · DE VOLTA AO MAPA':'SCENIC SCALE · BACK TO THE MAP',
  /* fichas: chaves rápidas */
  'DISTÂNCIA':'DISTANCE', 'RAIO':'RADIUS', 'TIPO':'TYPE', 'MASSA':'MASS', 'DESCOBERTA':'DISCOVERED', 'IDADE':'AGE', 'CATÁLOGO':'CATALOG', 'DIÂMETRO':'DIAMETER',
  'ESTRELAS':'STARS', 'LARGURA':'WIDTH', 'GRAVIDADE':'GRAVITY', 'ÓRBITA':'ORBIT', 'TEMP. SUP.':'SURF. TEMP.', 'ESTRELA':'STAR', 'NO BRASIL':'FROM BRAZIL', 'A OLHO NU':'NAKED EYE',
  'ÁGUA':'WATER', 'LANÇAMENTO':'LAUNCH', 'BRILHO':'BRIGHTNESS', 'TAMANHO':'SIZE', 'DESTINO':'DESTINATION', 'CONSTELAÇÃO':'CONSTELLATION', 'VELOCIDADE':'SPEED',
  'TEMP. EQ.':'EQ. TEMP.', 'ZONA':'ZONE', 'NO CÉU':'IN THE SKY', 'A PRINCIPAL':'THE MAIN ONE', 'VIZINHA':'NEIGHBOR', 'TEMP. MÉDIA':'MEAN TEMP.', 'ROTAÇÃO':'ROTATION',
  'NÚCLEO':'CORE', 'NA ZONA':'IN THE ZONE', 'MÉTODO':'METHOD', 'JATOS':'JETS', 'FORMA':'SHAPE', 'TRIPULAÇÃO':'CREW', 'RUMO':'HEADING', 'POUSO':'LANDING',
  'EXPLOSÃO':'EXPLOSION', 'EXPANSÃO':'EXPANSION', 'DETECTADO':'DETECTED', 'DESTAQUE':'HIGHLIGHT', 'ANÉIS':'RINGS', 'NOME':'NAME', 'DESCOBERTO':'DISCOVERED', 'COR':'COLOR',
  'COMPANHEIRA':'COMPANION', 'ALTURA':'HEIGHT', 'ZODÍACO':'ZODIAC', 'RETORNO':'RETURN', 'RECORDE':'RECORD', 'PAÍS':'COUNTRY', 'OCEANO':'OCEAN', 'EXTENSÃO':'EXTENT',
  'EXPLODIU':'EXPLODED', 'DIMENSÕES':'DIMENSIONS', 'DENSIDADE':'DENSITY', 'ATMOSFERA':'ATMOSPHERE', 'PERÍODO':'PERIOD', 'DURAÇÃO':'DURATION', 'HABITABILIDADE':'HABITABILITY',
  'PRESSÃO':'PRESSURE', 'INCLINAÇÃO':'TILT', 'SUPERFÍCIE':'SURFACE', 'COMPOSIÇÃO':'COMPOSITION', 'MISSÕES':'MISSIONS', 'MISSÃO':'MISSION', 'FIM':'END', 'CHEGADA':'ARRIVAL',
  'DIA (ROTAÇÃO)':'DAY (ROTATION)', 'ANO (ÓRBITA)':'YEAR (ORBIT)', 'TEMPERATURA':'TEMPERATURE', 'DISTÂNCIA DO SOL':'DISTANCE FROM THE SUN', 'LUZ DO SOL':'SUNLIGHT',
  /* registro de bordo */
  'REGISTRO DE BORDO':'LOGBOOK', 'CADETE':'CADET', 'APRENDIZ DE ROTA':'ROUTE APPRENTICE', 'NAVEGADOR':'NAVIGATOR', 'PILOTO DE LONGO CURSO':'LONG-HAUL PILOT',
  'CARTÓGRAFO':'CARTOGRAPHER', 'MESTRE CARTÓGRAFO':'MASTER CARTOGRAPHER', 'EXPLORADOR SÊNIOR':'SENIOR EXPLORER', 'ALMIRANTE DO VAZIO':'ADMIRAL OF THE VOID', 'CARTÓGRAFO-MOR':'CHIEF CARTOGRAPHER',
  'Ainda no cais.':'Still at the dock.', 'O primeiro link travado.':'The first locked link.', 'Já sabe ler uma carta estelar.':'Already reads a star chart.',
  'Sai do quintal sem se perder.':'Leaves the backyard without getting lost.', 'Desenha o que ninguém viu.':'Draws what nobody has seen.',
  'Metade do catálogo na memória.':'Half the catalog by heart.', 'Poucos lugares ainda te surpreendem.':'Few places still surprise you.',
  'Falta pouco para o catálogo inteiro.':'Almost the whole catalog.', 'Tudo visitado. O universo ficou pequeno.':'Everything visited. The universe got small.',
  '<b>0</b> / 0 VISITADOS':'<b>0</b> / 0 VISITED', 'BUSCAR NO CATÁLOGO…':'SEARCH THE CATALOG…', 'Limpar busca':'Clear search', 'Ordenar':'Sort', 'A a Z':'A to Z',
  'DISTÂNCIA DE CASA':'DISTANCE FROM HOME', 'FECHAR':'CLOSE', 'TUDO':'ALL', '★ SISTEMAS':'★ SYSTEMS', '⬡ CONQUISTAS':'⬡ ACHIEVEMENTS', 'A VISITAR':'TO VISIT', 'VISITADOS':'VISITED',
  'ONDE CHEGAMOS':'WHERE WE HAVE BEEN', 'NAVES':'SPACECRAFT', 'REGIÕES':'REGIONS', 'PLANETA':'PLANET', 'LUA':'MOON', 'REGIÃO':'REGION', 'CORPO MENOR':'MINOR BODY', 'NAVE':'SPACECRAFT',
  ' CORPOS VISITADOS':' BODIES VISITED', ' SISTEMAS · ':' SYSTEMS · ', ' GALÁXIAS':' GALAXIES', ' CONQUISTAS</span>':' ACHIEVEMENTS</span>', ' · FALTAM ':' · MISSING ',
  ' CONQUISTAS · CADA UMA VALE 2 CORPOS NA CARREIRA':' ACHIEVEMENTS · EACH ONE COUNTS AS 2 BODIES IN YOUR CAREER', 'CONCLUÍDA EM ':'COMPLETED ON ', ' · VISITADO':' · VISITED',
  'NENHUM SISTEMA ENCONTRADO':'NO SYSTEM FOUND', 'SISTEMA COMPLETO':'SYSTEM COMPLETE', ' SISTEMAS COMPLETOS':' SYSTEMS COMPLETE', ' SISTEMA COMPLETO':' SYSTEM COMPLETE',
  'CAD-01 · VISITAR UM CORPO':'CAD-01 · VISIT A BODY', 'CAD-02 · LIGAR A LINHA DAS SONDAS':'CAD-02 · TURN ON THE PROBES LINE', 'CAD-03 · LOCALIZAR PELA BUSCA':'CAD-03 · FIND WITH SEARCH',
  'CAD-04 · VISITAR 5 CORPOS DO SISTEMA SOLAR':'CAD-04 · VISIT 5 SOLAR SYSTEM BODIES', 'CAD-05 · PAUSAR E RETOMAR O RELÓGIO':'CAD-05 · PAUSE AND RESUME THE CLOCK',
  'CAD-06 · SUBIR ATÉ A GALÁXIA':'CAD-06 · GO UP TO THE GALAXY', 'CAD-07 · VISITAR UMA SONDA':'CAD-07 · VISIT A PROBE', 'TIM-01 · COMPARAR DOIS CORPOS':'TIM-01 · COMPARE TWO BODIES',
  'TIM-02 · VIAJAR NO TEMPO':'TIM-02 · TRAVEL THROUGH TIME', 'TIM-03 · REVIVER UMA MISSÃO APOLLO':'TIM-03 · RELIVE AN APOLLO MISSION', 'TIM-04 · COMPLETAR UM SISTEMA':'TIM-04 · COMPLETE A SYSTEM',
  'EXP-01 · COMPLETAR UMA ROTA DO TOUR':'EXP-01 · COMPLETE A TOUR ROUTE', 'EXP-02 · COMPLETAR TODAS AS ROTAS OFICIAIS':'EXP-02 · COMPLETE ALL OFFICIAL ROUTES',
  'EXP-03 · TOUR EM OUTRA GALÁXIA':'EXP-03 · TOUR IN ANOTHER GALAXY', 'EXP-04 · O SISTEMA EM VERDADEIRA GRANDEZA':'EXP-04 · THE SYSTEM AT TRUE SIZE',
  'CEU-01 · ACHAR O CRUZEIRO DO SUL':'CEU-01 · FIND THE SOUTHERN CROSS', 'CEU-02 · O DESENHO SE DESFEZ':'CEU-02 · THE DRAWING CAME UNDONE', 'CEU-03 · AS FIGURAS DO CÉU':'CEU-03 · THE FIGURES OF THE SKY',
  'CEU-04 · A VIZINHANÇA DO SOL':"CEU-04 · THE SUN'S NEIGHBORHOOD", 'EXP-05 · DE UM MUNDO À GALÁXIA, SEM CORTES':'EXP-05 · FROM A WORLD TO THE GALAXY, NO CUTS',
  'TIM-05 · A ERA COMPLETA':'TIM-05 · THE COMPLETE ERA', 'TIM-06 · O MUSEU INTEIRO':'TIM-06 · THE WHOLE MUSEUM',
  'Selecione um corpo e entre nele.':'Select a body and enter it.', 'No filtro ≋, ligue a linha das SONDAS.':'In the ≋ filter, turn on the PROBES line.',
  'Tecla S ou ⌕: busque um corpo e vá até ele.':'Key S or ⌕: search a body and go to it.', 'Entre em 5 corpos diferentes do Sistema Solar.':'Enter 5 different Solar System bodies.',
  'No relógio do canto, pause o tempo e retome.':'On the corner clock, pause time and resume.', 'Suba até a escala da galáxia.':'Go up to the galaxy scale.',
  'Selecione uma sonda (Voyager, Pioneer...) e entre nela.':'Select a probe (Voyager, Pioneer...) and enter it.', 'Use o ◫ para comparar dois corpos em escala real.':'Use ◫ to compare two bodies at real scale.',
  'No ◈ do relógio, viaje para outra data.':'In the clock ◈, travel to another date.', 'Abra a linha do tempo da Apollo 11 ou 13.':'Open the timeline of Apollo 11 or 13.',
  'Visite todos os corpos de um sistema.':'Visit every body of one system.', 'Deixe o TOUR (tecla T, ou ▶ no registro) completar uma rota inteira.':'Let the TOUR (key T, or ▶ in the logbook) complete a whole route.',
  'Complete todas as rotas oficiais da caixinha do tour.':'Complete every official route in the tour box.', 'Abra o card de um sistema fora da Via Láctea e rode o TOUR dele até o fim.':'Open the card of a system outside the Milky Way and run its TOUR to the end.',
  'Ligue a ESCALA REAL na engrenagem, entre na Terra e depois afaste até o sistema inteiro virar um pontinho.':'Turn on the REAL SCALE in the settings, enter Earth, then zoom out until the whole system becomes a dot.',
  'Na escala real, com as constelações ligadas, aproxime da Terra e gire o céu até encontrar o CRUZEIRO DO SUL.':'At real scale, with constellations on, get close to Earth and turn the sky until you find the SOUTHERN CROSS.',
  'Na escala 1:1, afaste o zoom até sair do Sistema Solar e ver as constelações começarem a se desmanchar.':'At 1:1 scale, zoom out until you leave the Solar System and see the constellations start to come undone.',
  'Abra a ficha das constelações do céu real, uma a uma.':'Open the card of each constellation in the real sky, one by one.', 'Abra a ficha de cada estrela a menos de 25 anos-luz do Sol.':'Open the card of every star within 25 light-years of the Sun.',
  'Na escala 1:1, entre num corpo e afaste o zoom sem trocar de cena até ver a Via Láctea inteira.':'At 1:1 scale, enter a body and zoom out without changing scene until you see the whole Milky Way.',
  'Reviva as linhas do tempo das seis missões lunares: Apollo 8, 11, 13, 17 e Artemis I e II.':'Relive the timelines of the six lunar missions: Apollo 8, 11, 13, 17 and Artemis I and II.',
  'Reviva as DEZ linhas do tempo lunares, da Luna 9 ao SLIM: o museu completo da corrida.':'Relive the TEN lunar timelines, from Luna 9 to SLIM: the complete museum of the race.',
  /* busca e comparar */
  'BUSCAR CORPO, SISTEMA OU GALÁXIA…':'SEARCH BODY, SYSTEM OR GALAXY…', '↑↓ NAVEGA · ENTER TRAVA ROTA · ESC FECHA':'↑↓ NAVIGATE · ENTER LOCKS ROUTE · ESC CLOSES',
  '◇ ANÁLISE COMPARATIVA':'◇ COMPARATIVE ANALYSIS',
  /* boot */
  'CALIBRANDO SENSORES ÓPTICOS ......... <span class="ok">OK</span>':'CALIBRATING OPTICAL SENSORS .......... <span class="ok">OK</span>',
  'LINK DE SATÉLITE 08 ................. <span class="ok">OK</span>':'SATELLITE LINK 08 ................... <span class="ok">OK</span>',
  'BEM-VINDO A BORDO, NAVEGADOR.':'WELCOME ABOARD, NAVIGATOR.',
  /* manual (parágrafos inteiros) */
  'MANUAL DO NAVEGADOR':"NAVIGATOR'S MANUAL",
  '<b>Toque</b> em um corpo para catalogar. Toque de novo (ou use o botão ▶ do card) para entrar.':'<b>Tap</b> a body to catalog it. Tap again (or use the ▶ button on the card) to enter.',
  '<b>Arraste</b> para girar<span class="kb"> · <b>scroll</b> para aproximar</span><span class="touchonly"> · <b>pinça</b> para aproximar. Os botões <b>+ / −</b> também ajustam o zoom</span>.':'<b>Drag</b> to rotate<span class="kb"> · <b>scroll</b> to zoom</span><span class="touchonly"> · <b>pinch</b> to zoom. The <b>+ / −</b> buttons also adjust the zoom</span>.',
  '<b>Afaste o zoom</b> até o limite para subir de escala: Corpo → Sistema → Galáxia → Universo. Ele trava no limite: afaste de novo para subir. A trilha no topo também navega.':'<b>Zoom out</b> to the limit to go up a scale: Body → System → Galaxy → Universe. It locks at the limit: zoom out again to go up. The breadcrumb at the top also navigates.',
  '<b>Botões ‹ ›</b> saltam entre planetas ou luas vizinhas<span class="kb">, assim como as setas do teclado</span>.':'<b>‹ › buttons</b> jump between neighboring planets or moons<span class="kb">, and so do the keyboard arrows</span>.',
  '<b>◫ Comparar:</b> toque no botão do card, abra outro corpo e toque de novo: análise lado a lado em escala real.':'<b>◫ Compare:</b> tap the button on the card, open another body and tap again: a side-by-side analysis at real scale.',
  '<b>▤ Registro de bordo:</b> a lista completa do catálogo, com o que você já visitou, sua patente, busca e filtros por habitáveis, planetas, luas, estrelas e regiões.':'<b>▤ Logbook:</b> the complete catalog, with what you have visited, your rank, search and filters for habitable worlds, planets, moons, stars and regions.',
  '<b>⌗ Modo foto:</b> esconde o painel inteiro para uma captura limpa<span class="touchonly">. Um toque longo na tela faz o mesmo</span><span class="kb"> (ou a tecla <b>P</b>)</span>.':'<b>⌗ Photo mode:</b> hides the whole panel for a clean capture<span class="touchonly">. A long press on the screen does the same</span><span class="kb"> (or the <b>P</b> key)</span>.',
  '<b>▶ Modo tour:</b> dentro do registro de bordo<span class="kb"> (ou pela tecla <b>T</b>)</span>, o mapa se guia sozinho por uma rota comentada. Toque na cena a qualquer momento para assumir o controle.':'<b>▶ Tour mode:</b> inside the logbook<span class="kb"> (or with the <b>T</b> key)</span>, the map guides itself along a narrated route. Tap the scene at any time to take control.',
  '<b>Compartilhe:</b> o endereço da página acompanha o objeto (ex.: <span style="font-family:var(--mono)">#corpo=europa</span>), copie o link e envie.':'<b>Share:</b> the page address follows the object (e.g. <span style="font-family:var(--mono)">#corpo=europa</span>), copy the link and send it.',
  'ESC volta um nível · / ou S busca · M registro · T tour · P foto · ? este manual':'ESC goes up one level · / or S search · M logbook · T tour · P photo · ? this manual',
  '<b>Relógio do sistema:</b> a data real corre no canto inferior esquerdo, com pause e viagem a qualquer data (◈). A velocidade fica nas configurações ⚙︎, do tempo real a 1 s = 1 mês.':'<b>System clock:</b> the real date runs in the bottom left corner, with pause and travel to any date (◈). The speed lives in the ⚙︎ settings, from real time to 1 s = 1 month.',
  '<b>⬡ Conquistas:</b> ações especiais (comparar, viajar no tempo, reviver uma Apollo) valem 2 corpos cada na carreira. A lista completa mora no registro de bordo.':'<b>⬡ Achievements:</b> special actions (comparing, time travel, reliving an Apollo) count as 2 bodies each in your career. The full list lives in the logbook.',
  '<b>Trava de centro:</b> selecionar um corpo no mapa faz a câmera orbitá-lo: dá para chegar perto de Saturno sem trocar de escala. ESC ou ✕ soltam.':'<b>Center lock:</b> selecting a body on the map makes the camera orbit it: you can get close to Saturn without changing scale. ESC or ✕ release it.',
  '<b>≋ Linha do tempo:</b> sondas, cometas e as Apollo têm a viagem reconstruída, com os planetas NA ÉPOCA certa e marcos clicáveis.':'<b>≋ Timeline:</b> probes, comets and the Apollo missions have their trip rebuilt, with the planets AT THE RIGHT TIME and clickable milestones.',
  '▸ REVER O TUTORIAL DE BOAS-VINDAS':'▸ REPLAY THE WELCOME TUTORIAL', 'UNIVERSATLAS · universatlas.com · o mapa Cartografia Estelar':'UNIVERSATLAS · universatlas.com · the Stellar Cartography map',
  'Dados: NASA/ESA/IAU, valores aproximados. Linhas em âmbar são referências de ficção.':'Data: NASA/ESA/IAU, approximate values. Amber lines are fiction references.',
  'IDEALIZADO E DESENVOLVIDO POR':'CONCEIVED AND DEVELOPED BY',
  /* rótulos do mapa */
  'ZONA HABITÁVEL':'HABITABLE ZONE', 'NUVEM DE OORT':'OORT CLOUD', 'LINHA DE GELO':'FROST LINE', 'HELIOPAUSA':'HELIOPAUSE', 'CINTURÃO DE KUIPER':'KUIPER BELT',
  'CINTURÃO DE ASTEROIDES':'ASTEROID BELT', 'CINTURÃO':'BELT', 'A ECLÍPTICA':'THE ECLIPTIC', 'CENTRO DA GALÁXIA':'GALACTIC CENTER', 'ANDRÔMEDA':'ANDROMEDA',
  'GRANDE NUVEM DE MAGALHÃES':'LARGE MAGELLANIC CLOUD', 'PEQUENA NUVEM DE MAGALHÃES':'SMALL MAGELLANIC CLOUD'
},
nomes: {
  sol:'SUN', mercurio:'MERCURY', venus:'VENUS', terra:'EARTH', lua:'MOON', marte:'MARS', fobos:'PHOBOS', jupiter:'JUPITER', ganimedes:'GANYMEDE', calisto:'CALLISTO',
  saturno:'SATURN', tita:'TITAN', reia:'RHEA', encelado:'ENCELADUS', tetis:'TETHYS', hiperion:'HYPERION', japeto:'IAPETUS', febe:'PHOEBE', urano:'URANUS', titania:'TITANIA',
  netuno:'NEPTUNE', tritao:'TRITON', plutao:'PLUTO', caronte:'CHARON', eris:'ERIS', p67:'COMET 67P', halley:"HALLEY'S COMET", cinturao:'ASTEROID BELT', kuiper:'KUIPER BELT',
  oort:'OORT CLOUD', palas:'PALLAS',
  k16b_star:'KEPLER-16 B (STAR)', vegadisk:'VEGA DEBRIS DISK', fomdisk:'FOMALHAUT RING', barnardstar:"BARNARD'S STAR", pilares:'PILLARS OF CREATION', trapezio:'TRAPEZIUM',
  nebulosaorion:'ORION NEBULA', pulsarcaranguejo:'CRAB PULSAR', caranguejo:'CRAB NEBULA', m57centro:'WHITE DWARF OF THE RING', anel:'RING NEBULA', alcyone:'ALCYONE', pleiades:'PLEIADES',
  gatocentro:"CAT'S EYE CORE", olhodegato:"CAT'S EYE", formigacentro:'ANT NEBULA CORE', formiganeb:'ANT NEBULA', chama:'FLAME NEBULA', tuc47core:'47 TUC CORE',
  nuvem346:'NGC 346 CLOUD', tarantula:'TARANTULA NEBULA', roseta:'ROSETTE NEBULA', bajamar:'BAJAMAR STAR', namneb:'NORTH AMERICA', olhostar:'NGC 6543 CENTRAL', olhoneb:"CAT'S EYE",
  carinaneb:'CARINA NEBULA', omegacore:'OMEGA CORE', omegacentauri:'OMEGA CENTAURI', progenitorveu:'THE STAR THAT EXPLODED', veu:'VEIL NEBULA', lagoa:'LAGOON NEBULA', trifida:'TRIFID NEBULA',
  cabecacavalo:'HORSEHEAD', pa99lente:'LENS STAR PA-99-N2', g1nucleo:'G1 CORE', g1enxame:'MAYALL II SWARM', p2buraco:'M31 BLACK HOLE', p1disco:'P1 DISK'
},
sis: {
  sol:'SOLAR SYSTEM', sirius:'SIRIUS SYSTEM', barnard:"BARNARD'S STAR", m16:'EAGLE NEBULA', orion:'ORION NEBULA', caranguejo:'CRAB NEBULA', m57:'RING NEBULA', cavalo:'HORSEHEAD',
  gato:"CAT'S EYE", norteamerica:'NORTH AMERICA', formiga:'ANT NEBULA', pleiades:'PLEIADES', chama:'FLAME NEBULA', tarantula:'TARANTULA NEBULA', roseta:'ROSETTE NEBULA',
  olhodegato:"CAT'S EYE", carina:'CARINA NEBULA', omega:'OMEGA CENTAURI', veu:'VEIL NEBULA', lagoa:'LAGOON NEBULA', trifida:'TRIFID NEBULA', nucleoM31:'ANDROMEDA CORE'
},
marcadores: {
  m16:'PILLARS OF CREATION', caranguejo:'CRAB · M1', pleiades:'PLEIADES · M45', tarantula:'TARANTULA · 30 DOR', nucleoM31:'M31 CORE'
},
gal: {
  vialactea:'MILKY WAY', andromeda:'ANDROMEDA · M31', triangulo:'TRIANGULUM · M33', magalhaes:'LARGE MAGELLANIC CLOUD', pnm:'SMALL MAGELLANIC CLOUD', redemoinho:'WHIRLPOOL · M51'
},
ceu: {
  orion:'ORION', cruzeiro:'SOUTHERN CROSS', ursamaior:'URSA MAJOR', cassiopeia:'CASSIOPEIA', escorpiao:'SCORPIUS', touro:'TAURUS', gemeos:'GEMINI', leao:'LEO', virgem:'VIRGO',
  cisne:'CYGNUS', lira:'LYRA', aguia:'AQUILA', sagitario:'SAGITTARIUS', centauro:'CENTAURUS', caomaior:'CANIS MAJOR', perseu:'PERSEUS', andromeda:'ANDROMEDA', pegaso:'PEGASUS',
  boieiro:'BOOTES', ursamenor:'URSA MINOR', caomenor:'CANIS MINOR', serpente:'SERPENS', ofiuco:'OPHIUCHUS'
},
/* troca de PALAVRAS em designações compostas (ordem importa: as longas primeiro) */
palavras: [
  ['VISITANTE INTERESTELAR','INTERSTELLAR VISITOR'], ['COMETA DE LONGO PERÍODO','LONG-PERIOD COMET'], ['COMETA PERIÓDICO','PERIODIC COMET'], ['PLANETA ANÃO','DWARF PLANET'],
  ['REGIÃO TRANSNETUNIANA','TRANS-NEPTUNIAN REGION'], ['TRANSNETUNIANO','TRANS-NEPTUNIAN'], ['FRONTEIRA FINAL','FINAL FRONTIER'], ['MISSÃO TRIPULADA','CREWED MISSION'],
  ['MISSÃO ROBÓTICA','ROBOTIC MISSION'], ['CÍRCULO DO CÉU','SKY CIRCLE'], ['O PLANO DA ÓRBITA','THE ORBITAL PLANE'], ['MIL ANOS-LUZ','THOUSAND LIGHT-YEARS'], ['ANOS-LUZ','LIGHT-YEARS'],
  ['AGLOMERADO GLOBULAR','GLOBULAR CLUSTER'], ['AGLOMERADO ABERTO','OPEN CLUSTER'], ['AGLOMERADO','CLUSTER'], ['NEBULOSA PLANETÁRIA','PLANETARY NEBULA'], ['NEBULOSA DE EMISSÃO','EMISSION NEBULA'],
  ['NEBULOSA','NEBULA'], ['RESTO DE SUPERNOVA','SUPERNOVA REMNANT'], ['BERÇÁRIO ESTELAR','STELLAR NURSERY'], ['BURACO NEGRO','BLACK HOLE'], ['ANÃ BRANCA','WHITE DWARF'],
  ['SUPERGIGANTE','SUPERGIANT'], ['GIGANTE','GIANT'], ['ESTRELA','STAR'], ['EXOPLANETA','EXOPLANET'], ['PLANETA','PLANET'], ['SATÉLITE','SATELLITE'], ['TELESCÓPIO','TELESCOPE'],
  ['ESTAÇÃO','STATION'], ['SONDA','PROBE'], ['MISSÃO','MISSION'], ['PREVISTA','PLANNED'], ['COMETA','COMET'], ['REGIÃO','REGION'], ['FRONTEIRA','FRONTIER'], ['ASTEROIDE','ASTEROID'],
  ['PROTOPLANETA','PROTOPLANET'], ['CINTURÃO','BELT'], ['CONFINS','OUTER REACHES'], ['FAIXA','BAND'], ['CANDIDATO','CANDIDATE'], ['COMPANHEIRA','COMPANION'], ['BINÁRIA','BINARY'],
  ['MÚLTIPLO','MULTIPLE'], ['QUENTE','HOT'], ['PEQUENA','SMALL'], ['NÚCLEO','CORE'], ['NUVEM','CLOUD'], ['DISCO','DISK'], ['DETRITOS','DEBRIS'], ['MORIBUNDA','DYING'], ['VELOZ','FAST'],
  ['TRÍPLICE','TRIPLE'], ['SUPER-TERRA','SUPER-EARTH'], ['EXTRAGALÁCTICO','EXTRAGALACTIC'], ['CENTRO','CENTER'], ['SISTEMA','SYSTEM'], ['CONFIRMADAS','CONFIRMED'], ['PRINCIPAIS','MAIN'],
  ['GALILEANAS','GALILEAN'], ['TERRA-','EARTH-'], ['MARTE-','MARS-'], ['JÚPITER-','JUPITER-'], ['SATURNO-','SATURN-'], ['URANO-','URANUS-'], ['NETUNO-','NEPTUNE-'], ['PLUTÃO-','PLUTO-'],
  ['SOL-','SUN-'], ['SOL ·','SUN ·'], ['LUA','MOON'], ['ANÃO','DWARF'], ['ANÃ','DWARF'], ['AZUL','BLUE'], ['BRANCA','WHITE'], ['NEGRO','BLACK'], [' DE ',' OF '], [' DA ',' OF '], [' DO ',' OF '],
  [' E ',' AND '], [' UA',' AU']
]
};
